//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcusesInventario_Temporal : BaseEntity
    {
        public string Nro_Plastico { get; set; }
        public string Id_Embozo { get; set; }
        public string Fecha_Embozado { get; set; }
        public string BarCode_Pieza { get; set; }
        public string Rechazo { get; set; }
        public string ErrorTipoDato { get; set; }
        public string Motivo_Rechazo { get; set; }
        public string Marca { get; set; }
        public string Fecha_Alta { get; set; }
        public string Registro { get; set; }
        public string Id_Producto { get; set; }
        public string Id_Sucursal { get; set; }
        public string Tipo_Documento { get; set; }
        public string Nro_documento { get; set; }
        public string Apellido_nombre { get; set; }
        public string Embozado { get; set; }
        public string Motivo_Impresion { get; set; }
        public string GAF { get; set; }
        public string Origen_Embozo { get; set; }
        public string NombreArchivo { get; set; }
        public string NroCuenta { get; set; }
    }
}
