//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas : BaseEntity
    {
        public decimal aleID { get; set; }
        public string aleAsunto { get; set; }
        public string aleCuerpo { get; set; }
        public string aleMailPrincipal { get; set; }
        public string aleMailCopia { get; set; }
        public string aleArchivo { get; set; }
        public Nullable<decimal> aleFecha { get; set; }
        public Nullable<decimal> aleEnvios { get; set; }
        public Nullable<decimal> aleFechaUltEnvio { get; set; }
        public Nullable<decimal> aleTotalEnvios { get; set; }
        public string aleActiva { get; set; }
    }
}
