//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AlertasPlastico : BaseEntity
    {
        [Key]
        public decimal aplId { get; set; }
        public decimal adeId { get; set; }
        public decimal aplNumero { get; set; }
        public decimal aplFecha { get; set; }
        public string aplError { get; set; }
        public Nullable<decimal> aplEmbozo { get; set; }
    
        public virtual AlertasDestinos AlertasDestinos { get; set; }
    }
}
