//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canales : BaseEntity
    {
        public decimal canID { get; set; }
        public string canDes { get; set; }
        public string canObservacion { get; set; }
        public string canActivo { get; set; }
    }
}
