//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribucionConfig : BaseEntity
    {
        public decimal dicId { get; set; }
        public string dicMarca { get; set; }
        public string dicProducto { get; set; }
        public string dicMotImpresion { get; set; }
        public Nullable<decimal> dicGAF { get; set; }
        public string dicCanalOrigen { get; set; }
        public string dicPermisionaria { get; set; }
        public string dicModEntrega { get; set; }
        public string dicHabilitada { get; set; }
        public string dicUsuario { get; set; }
        public System.DateTime dicFecha { get; set; }
    }
}
