//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Estados
	{
		//[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		//public Estados()
		//{
		//	this.AlertasTiposEmail = new HashSet<AlertasTiposEmail>();
		//}

		[Key]
		public decimal estId { get; set; }
        public string estDes { get; set; }
        public Nullable<decimal> catID_est { get; set; }
        public Nullable<int> estHablitaRecepcionFisicoyPlastico { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<AlertasTiposEmail> AlertasTiposEmail { get; set; }//no

    }
}
