//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Estados_Secuencia : BaseEntity
    {
        [Key]
        public decimal cxeID { get; set; }
        public Nullable<decimal> cxeEstadoOrigen { get; set; }
        public Nullable<decimal> cxeEstadoDestino { get; set; }
        public Nullable<decimal> cxeRol { get; set; }
        public Nullable<bool> cxeDireccion { get; set; }
        public Nullable<int> cxeHabilitaModDoc { get; set; }
        public Nullable<int> cxeManual { get; set; }
        public Nullable<int> cxeAsignarCuentaDebito { get; set; }
        public Nullable<int> cxeActualizarClientesWeb { get; set; }
        public Nullable<int> cxeControlarCuentaDebito { get; set; }
        public Nullable<int> cxeMargen_accion { get; set; }
        public Nullable<int> cxeValida_Margen { get; set; }
        public int tipoSolicitud_id { get; set; }
        public bool cxeModificaOtraSuc { get; set; }
        public bool cxeEstadoMasivo { get; set; }
        public Nullable<bool> cxeModificaSucRad { get; set; }
        public Nullable<bool> cxeHabCboSuc { get; set; }
        public Nullable<bool> cxeObligaReversa { get; set; }
        public Nullable<bool> cxeAlerta { get; set; }
    }
}
