//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mensajes : BaseEntity
    {
        [Key]
        public string sis_id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public bool habilita_envio { get; set; }
        public string destinatarios { get; set; }
        public string cuerpo { get; set; }
    }
}
