//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlasticosPendientes_Temporal : BaseEntity
    {
        public int Id { get; set; }
        public string Nro_Tarjeta { get; set; }
        public string Domicilio { get; set; }
        public string Localidad { get; set; }
        public string Codigo_Postal { get; set; }
        public string Entidad_Otorgante { get; set; }
        public string Sucursal_Otorgante { get; set; }
        public string Denominacion { get; set; }
        public string Numero_Acuse { get; set; }
        public string Nombre_Archivo { get; set; }
    }
}
