//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosTC : BaseEntity
    {
        public int Id { get; set; }
        public int MarcaProductoId { get; set; }
        public string NombreProducto { get; set; }
        public string CodigoBco { get; set; }
        public string Codigo_SOB { get; set; }
        public string CodigoMarca { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string MotivoBaja { get; set; }
        public string NombreCajonMargenesSAP { get; set; }
        public string Imagen { get; set; }
        public string NombreCajonNosis { get; set; }
        public string GAF { get; set; }
    }
}
