//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursosHumanos : BaseEntity
    {
        public decimal rhId { get; set; }
        public Nullable<decimal> rhLegajo { get; set; }
        public string rhApellidoNombre { get; set; }
        public Nullable<decimal> rhIdFuncion { get; set; }
        public string rhDescFuncion { get; set; }
        public Nullable<decimal> rhIdPosicion { get; set; }
        public string rhDescPosicion { get; set; }
        public Nullable<decimal> rhIdUnidadOrganizativa { get; set; }
        public string rhDescUnidadOrganizativa { get; set; }
        public Nullable<decimal> rhIdDivisionPersonal { get; set; }
        public string rhDescDivisionPersonal { get; set; }
        public string rhTipoSucursal { get; set; }
        public Nullable<decimal> rhLegajoJefe1 { get; set; }
        public string rhNombreJefe1 { get; set; }
        public string rhDescFuncionJefe1 { get; set; }
        public string rhDescripcionUO1 { get; set; }
        public Nullable<decimal> rhLegajoJefe2 { get; set; }
        public string rhNombreJefe2 { get; set; }
        public string rhDescFuncionJefe2 { get; set; }
        public string rhDescripcionUO2 { get; set; }
        public string rhUsuario { get; set; }
        public string rhEmail { get; set; }
    }
}
