//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes_Seguimiento : BaseEntity
    {
        public decimal sseID { get; set; }
        public decimal solId { get; set; }
        public decimal estId { get; set; }
        public decimal rchID { get; set; }
        public System.DateTime sseFecha { get; set; }
        public string usr { get; set; }
        public string obs { get; set; }
        public Nullable<bool> sseDireccion { get; set; }
        public Nullable<int> justificacionDestruccionId { get; set; }
    }
}
