//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trazabilidad.Core.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Solicitudes_Seguimiento : BaseEntity
    {
        [Key,Column (Order =0), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //[Column("sseID")]
        public decimal sseID { get; set; }
        public decimal solId { get; set; }
        public decimal estId { get; set; }
        public decimal rchID { get; set; }
        public System.DateTime sseFecha { get; set; }
        public string usr { get; set; }
        public string obs { get; set; }
        public Nullable<bool> sseDireccion { get; set; }
        public Nullable<int> justificacionDestruccionId { get; set; }

        //[Key]
        //[Column(TypeName = "numeric")]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //public decimal sseID { get; set; }

        //[Column(TypeName = "numeric")]
        //public decimal solId { get; set; }

        //[Column(TypeName = "numeric")]
        //public decimal estId { get; set; }

        //[Column(TypeName = "numeric")]
        //public decimal rchID { get; set; }

        //[Column(TypeName = "smalldatetime")]
        //public DateTime sseFecha { get; set; }

        //[Required]
        //[StringLength(30)]
        //public string usr { get; set; }

        //[StringLength(500)]
        //public string obs { get; set; }

        //public bool? sseDireccion { get; set; }

        //public int? justificacionDestruccionId { get; set; }
    }
}
